# Generated by Django 5.2.17 on 2026-10-04 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatabaseTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. stage, prod-eu, prod-us",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField(default=5432)),
                (
                    "dbname",
                    models.CharField(max_length=255, verbose_name="Database name"),
                ),
                ("user", models.CharField(max_length=255)),
                ("password_encrypted", models.TextField(blank=True)),
                (
                    "sslmode",
                    models.CharField(
                        choices=[
                            ("disable", "disable"),
                            ("allow", "allow"),
                            ("prefer", "prefer"),
                            ("require", "require"),
                            ("verify-ca", "verify-ca"),
                            ("verify-full", "verify-full"),
                        ],
                        default="prefer",
                        max_length=20,
                    ),
                ),
                ("schema", models.CharField(default="public", max_length=255)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Release / feature set of this environment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "path",
                    models.CharField(
                        help_text="Folder containing manage.py", max_length=500
                    ),
                ),
                (
                    "python_path",
                    models.CharField(
                        help_text="The project's venv interpreter, e.g. /path/venv/bin/python",
                        max_length=500,
                    ),
                ),
                (
                    "settings_module",
                    models.CharField(
                        blank=True,
                        help_text="e.g. config.settings — read from manage.py if blank",
                        max_length=200,
                    ),
                ),
                (
                    "extra_env",
                    models.TextField(
                        blank=True,
                        help_text="KEY=VALUE per line, needed for the settings to import",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ComparisonRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("project_name", models.CharField(max_length=100)),
                ("database_name", models.CharField(max_length=100)),
                ("git_branch", models.CharField(blank=True, max_length=255)),
                ("git_commit", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="ok", max_length=10)),
                ("error", models.TextField(blank=True)),
                ("options", models.JSONField(default=dict)),
                ("summary", models.JSONField(default=dict)),
                ("report", models.JSONField(default=dict)),
                ("fix_sql", models.TextField(blank=True)),
                (
                    "database",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="validator.databasetarget",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="validator.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
    ]
