# Generated by Django 5.2.17 on 2026-10-05 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(default="queued", max_length=12)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("log", models.TextField(blank=True)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("result_url", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="comparisonrun",
            name="kind",
            field=models.CharField(default="branch", max_length=10),
        ),
        migrations.AddField(
            model_name="comparisonrun",
            name="reference_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="databasetarget",
            name="environment",
            field=models.CharField(
                choices=[("dev", "dev"), ("stage", "stage"), ("prod", "prod")],
                default="dev",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="databasetarget",
            name="operation_timeout_s",
            field=models.PositiveIntegerField(
                default=300,
                help_text="statement_timeout for write operations",
                verbose_name="Operation timeout (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="databasetarget",
            name="write_password_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="databasetarget",
            name="write_user",
            field=models.CharField(
                blank=True,
                help_text="Separate user for writes; blank uses the user above",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="databasetarget",
            name="writes_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow deletes, cleanups and column drops on this database from the UI",
            ),
        ),
        migrations.CreateModel(
            name="CleanupRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("root_table", models.CharField(max_length=255)),
                ("filters", models.JSONField(default=list)),
                ("batch_size", models.PositiveIntegerField(default=5000)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Used for cascade rules (on_delete); strongly recommended",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="validator.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IgnoreRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Blank = any kind of finding",
                        max_length=40,
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="Object to match, wildcards allowed: legacy_*, billing*",
                        max_length=300,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "database",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank = every database",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="validator.databasetarget",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank = every project",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="validator.project",
                    ),
                ),
            ],
            options={
                "ordering": ["pattern"],
            },
        ),
        migrations.CreateModel(
            name="DataOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("delete", "Delete rows"),
                            ("cleanup", "Cleanup"),
                            ("drop_column", "Drop column"),
                        ],
                        max_length=12,
                    ),
                ),
                ("database_name", models.CharField(max_length=100)),
                ("environment", models.CharField(max_length=10)),
                ("root_table", models.CharField(max_length=255)),
                ("column", models.CharField(blank=True, max_length=255)),
                ("filters", models.JSONField(default=list)),
                ("cascade_overrides", models.JSONField(default=list)),
                ("batch_size", models.PositiveIntegerField(default=0)),
                ("plan", models.JSONField(default=dict)),
                ("planned_at", models.DateTimeField(blank=True, null=True)),
                ("rehearsal", models.JSONField(default=dict)),
                ("confirmation", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(default="planning", max_length=12)),
                ("counts", models.JSONField(default=dict)),
                ("backup_dir", models.CharField(blank=True, max_length=500)),
                ("sql_log", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "database",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="validator.databasetarget",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="validator.project",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="validator.cleanuprecipe",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="validator.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit", models.CharField(max_length=64)),
                ("status_hash", models.CharField(max_length=64)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="validator.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
