import psycopg
import pytest

from validator.db_inspector import InspectError, check_connection, connect, inspect_database
from tests.conftest import pg_execute

SCHEMA_SQL = [
    "CREATE TABLE parent (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code varchar(20) NOT NULL UNIQUE)",
    """CREATE TABLE child (
        id serial PRIMARY KEY,
        parent_id bigint NOT NULL REFERENCES parent(id),
        name character varying(50),
        amount numeric(10, 2) NOT NULL DEFAULT 0,
        created timestamp with time zone NOT NULL,
        UNIQUE (parent_id, name)
    )""",
    "CREATE INDEX child_created_idx ON child (created)",
    "CREATE UNIQUE INDEX child_lower_name ON child (lower(name))",
    "CREATE VIEW child_view AS SELECT * FROM child",
    "CREATE TABLE django_migrations (id bigserial PRIMARY KEY, app varchar(255) NOT NULL, name varchar(255) NOT NULL, applied timestamptz NOT NULL)",
    "INSERT INTO django_migrations (app, name, applied) VALUES ('shop', '0001_initial', now()), ('shop', '0002_x', now())",
]


def test_reads_tables_columns_constraints(pg_conninfo):
    pg_execute(pg_conninfo, SCHEMA_SQL)
    result = inspect_database(pg_conninfo, "public")
    child = result["tables"]["child"]
    assert child["columns"]["name"] == {"type": "character varying(50)", "nullable": True, "has_default": False}
    assert child["columns"]["amount"]["has_default"] is True
    assert child["columns"]["id"]["type"] == "integer"
    assert child["pk"] == ["id"]
    assert ["parent_id", "name"] in child["uniques"]
    assert child["fks"] == [{"columns": ["parent_id"], "ref_table": "parent", "ref_columns": ["id"]}]
    assert ["created"] in child["indexes"]
    # expression indexes are ignored rather than reported as a column set
    assert all(None not in cols for cols in child["uniques"] + child["indexes"])
    assert result["tables"]["parent"]["uniques"] == [["code"]]
    assert result["tables"]["parent"]["columns"]["id"]["has_default"] is True  # identity
    assert result["views"] == ["child_view"]
    assert [(m["app"], m["name"]) for m in result["migrations"]] == [
        ("shop", "0001_initial"), ("shop", "0002_x"),
    ]


def test_missing_django_migrations_table(pg_conninfo):
    pg_execute(pg_conninfo, "CREATE TABLE t (id int)")
    assert inspect_database(pg_conninfo, "public")["migrations"] is None


def test_non_public_schema(pg_conninfo):
    pg_execute(pg_conninfo, ["CREATE SCHEMA app", "CREATE TABLE app.thing (id int PRIMARY KEY)", "CREATE TABLE other (id int)"])
    result = inspect_database(pg_conninfo, "app")
    assert list(result["tables"]) == ["thing"]


def test_unknown_schema(pg_conninfo):
    with pytest.raises(InspectError, match="Schema 'nope' not found"):
        inspect_database(pg_conninfo, "nope")


def test_session_is_read_only(pg_conninfo):
    with connect(pg_conninfo) as conn:
        with pytest.raises(psycopg.errors.ReadOnlySqlTransaction):
            conn.execute("CREATE TABLE should_fail (id int)")


def test_query_count_independent_of_table_count(pg_conninfo):
    pg_execute(pg_conninfo, [f"CREATE TABLE t{i} (id int PRIMARY KEY, v text)" for i in range(30)])
    result = inspect_database(pg_conninfo, "public")
    assert len(result["tables"]) == 30
    assert result["query_count"] <= 7


def test_bad_credentials(pg_conninfo):
    with pytest.raises(InspectError):
        inspect_database({**pg_conninfo, "password": "wrong", "user": "nobody"}, "public")


def test_check_connection_returns_version(pg_conninfo):
    assert "PostgreSQL" in check_connection(pg_conninfo)
