from validator.fix_sql import build_commands, build_fix_sql
from validator.schema_diff import finding

HEADER = {"project": "backend", "branch": "feature/x", "commit": "abc123", "database": "stage",
          "schema": "public", "generated": "2026-10-04 10:00"}

CATEGORY_SQL = [
    'CREATE TABLE "shop_category" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL UNIQUE);',
]
PRODUCT_SQL = [
    'CREATE TABLE "shop_product" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "category_id" bigint NOT NULL, "name" varchar(200) NOT NULL);',
    'ALTER TABLE "shop_product" ADD CONSTRAINT "shop_product_category_id_name_9f_uniq" UNIQUE ("category_id", "name");',
    'ALTER TABLE "shop_product" ADD CONSTRAINT "shop_product_category_id_35_fk_shop_category_id" FOREIGN KEY ("category_id") REFERENCES "shop_category" ("id") DEFERRABLE INITIALLY DEFERRED;',
    'CREATE INDEX "shop_product_category_id_35" ON "shop_product" ("category_id");',
    'CREATE INDEX "shop_product_name_ab" ON "shop_product" ("name");',
    'CREATE INDEX "shop_product_name_ab_like" ON "shop_product" ("name" varchar_pattern_ops);',
]


def col(name, db_type, null=False, has_default=False):
    return {"name": name, "db_type": db_type, "null": null, "has_default": has_default, "has_db_default": False}


MODELS = [
    {"app_label": "shop", "model": "Product", "db_table": "shop_product", "managed": True,
     "columns": [col("id", "bigint"), col("category_id", "bigint"), col("name", "varchar(200)"),
                 col("sku", "varchar(40)", has_default=True), col("code", "varchar(10)")],
     "create_sql": PRODUCT_SQL,
     "add_column_sql": {
         "sku": ['ALTER TABLE "shop_product" ADD COLUMN "sku" varchar(40) DEFAULT \'\' NOT NULL;',
                 'ALTER TABLE "shop_product" ALTER COLUMN "sku" DROP DEFAULT;'],
         "code": ['ALTER TABLE "shop_product" ADD COLUMN "code" varchar(10) NOT NULL;'],
     }},
    {"app_label": "shop", "model": "Category", "db_table": "shop_category", "managed": True,
     "columns": [col("id", "bigint"), col("name", "varchar(100)")], "create_sql": CATEGORY_SQL,
     "add_column_sql": {}},
]


def build(schema=(), migrations=(), **options):
    opts = {"history_strategy": "fake", "include_other_apps": False, **options}
    return build_fix_sql(header=HEADER, models=MODELS, schema_findings=list(schema),
                         migration_findings=list(migrations), pending_changes={}, options=opts)


def test_nothing_to_do():
    sql = build()
    assert "Nothing to do" in sql
    assert "BEGIN;" not in sql


def test_header_and_transaction():
    sql = build([finding("table_missing", "error", "shop", "shop_category", "m")])
    assert sql.startswith("-- Schema Sync fix: backend @ feature/x (abc123) -> stage")
    assert "REVIEW BEFORE RUNNING" in sql
    assert sql.index("BEGIN;") < sql.index("CREATE TABLE") < sql.index("COMMIT;")


def test_missing_tables_create_before_constraints():
    sql = build([finding("table_missing", "error", "shop", "shop_product", "m"),
                 finding("table_missing", "error", "shop", "shop_category", "m")])
    creates = [sql.index('CREATE TABLE "shop_product"'), sql.index('CREATE TABLE "shop_category"')]
    assert max(creates) < sql.index("FOREIGN KEY")


def test_unmanaged_missing_table_not_created():
    sql = build([finding("table_missing", "info", "shop", "shop_category", "m")])
    assert "CREATE TABLE" not in sql


def test_add_column_uses_extractor_sql_and_warns_on_not_null_without_default():
    sql = build([finding("column_missing", "error", "shop", "shop_product", "m", "sku"),
                 finding("column_missing", "error", "shop", "shop_product", "m", "code")])
    assert 'ADD COLUMN "sku" varchar(40) DEFAULT \'\' NOT NULL;' in sql
    code_at = sql.index('ADD COLUMN "code"')
    assert "WARNING" in sql[sql.rindex("\n--", 0, code_at) - 200:code_at]


def test_type_change_and_null_changes():
    sql = build([
        finding("type_mismatch", "error", "shop", "shop_product", "m", "name", {"expected": "varchar(200)", "actual": "varchar(100)"}),
        finding("null_mismatch", "warning", "shop", "shop_product", "m", "category_id", {"expected_null": False}),
        finding("null_mismatch", "error", "shop", "shop_product", "m", "code", {"expected_null": True}),
    ])
    assert 'ALTER TABLE "shop_product" ALTER COLUMN "name" TYPE varchar(200) USING "name"::varchar(200);' in sql
    assert 'ALTER TABLE "shop_product" ALTER COLUMN "category_id" SET NOT NULL;' in sql
    assert 'ALTER TABLE "shop_product" ALTER COLUMN "code" DROP NOT NULL;' in sql


def test_missing_fk_unique_index_reuse_django_statements():
    sql = build([
        finding("fk_missing", "warning", "shop", "shop_product", "m", "category_id",
                {"ref_table": "shop_category", "ref_column": "id"}),
        finding("unique_missing", "warning", "shop", "shop_product", "m", "category_id,name",
                {"columns": ["category_id", "name"]}),
        finding("index_missing", "info", "shop", "shop_product", "m", "name", {"columns": ["name"]}),
    ])
    assert PRODUCT_SQL[1] in sql and PRODUCT_SQL[2] in sql
    assert PRODUCT_SQL[4] in sql and PRODUCT_SQL[5] in sql  # index and its _like twin
    assert PRODUCT_SQL[3] not in sql


def test_unique_without_statement_gets_generated_constraint():
    sql = build([finding("unique_missing", "warning", "shop", "shop_category", "m", "name", {"columns": ["name"]})])
    assert 'ALTER TABLE "shop_category" ADD CONSTRAINT "shop_category_name_uniq" UNIQUE ("name");' in sql


def test_extras_are_commented_out():
    sql = build([finding("table_extra", "warning", "shop", "shop_legacy", "m"),
                 finding("column_extra", "warning", "shop", "shop_product", "m", "old")])
    for line in sql.splitlines():
        if "DROP TABLE" in line or "DROP COLUMN" in line:
            assert line.startswith("-- ")
    assert '-- DROP TABLE "shop_legacy";' in sql
    assert '-- ALTER TABLE "shop_product" DROP COLUMN "old";' in sql


def test_history_fake_strategy():
    sql = build(migrations=[
        finding("ghost", "error", "shop", "", "m", "0009_gone", {"name": "0009_gone"}),
        finding("unapplied", "info", "shop", "", "m", "0003_new", {"name": "0003_new"}),
    ])
    assert "DELETE FROM \"django_migrations\" WHERE app = 'shop' AND name = '0009_gone';" in sql
    assert "INSERT INTO \"django_migrations\" (app, name, applied) VALUES ('shop', '0003_new', now());" in sql


def test_history_leave_strategy():
    sql = build(migrations=[
        finding("ghost", "error", "shop", "", "m", "0009_gone", {"name": "0009_gone"}),
        finding("unapplied", "info", "shop", "", "m", "0003_new", {"name": "0003_new"}),
    ], history_strategy="leave")
    assert "DELETE FROM" in sql
    assert "INSERT INTO" not in sql


def test_other_app_rows_only_with_option():
    rows = [finding("other_app_rows", "warning", "billing", "", "m", data={"names": ["0001_initial"]})]
    assert "DELETE FROM \"django_migrations\" WHERE app = 'billing'" not in build(migrations=rows)
    assert "kept" in build(migrations=rows)
    assert "DELETE FROM \"django_migrations\" WHERE app = 'billing' AND name = '0001_initial';" in build(
        migrations=rows, include_other_apps=True)


def test_history_missing_creates_table_when_faking():
    sql = build(migrations=[finding("history_missing", "error", "", "", "m"),
                            finding("unapplied", "info", "shop", "", "m", "0001_initial", {"name": "0001_initial"})])
    assert sql.index('CREATE TABLE "django_migrations"') < sql.index("INSERT INTO")


def test_quotes_are_escaped():
    sql = build(migrations=[finding("ghost", "error", "shop", "", "m", "0009_it's", {"name": "0009_it's"})])
    assert "name = '0009_it''s'" in sql


def test_non_public_schema_sets_search_path():
    sql = build_fix_sql(header={**HEADER, "schema": "tenant"}, models=MODELS,
                        schema_findings=[finding("table_missing", "error", "shop", "shop_category", "m")],
                        migration_findings=[], pending_changes={},
                        options={"history_strategy": "fake", "include_other_apps": False})
    assert 'SET LOCAL search_path TO "tenant";' in sql


def test_commands():
    findings = [finding("ghost", "error", "shop", "", "m", "0009_gone", {"name": "0009_gone"}),
                finding("unapplied", "info", "orders", "", "m", "0002_x", {"name": "0002_x"})]
    per_app = {"shop": {"disk_leaf": ["0003_a"]}, "orders": {"disk_leaf": ["0002_x"]}}
    assert build_commands(findings, per_app, {"history_strategy": "fake"}) == [
        "python manage.py migrate shop --prune",
        "python manage.py migrate orders 0002_x --fake",
    ]
    assert build_commands(findings, per_app, {"history_strategy": "leave"}) == [
        "python manage.py migrate shop --prune",
    ]
