"""Build the fix script for one comparison. The tool never executes it."""
import re

DJANGO_MIGRATIONS_DDL = (
    'CREATE TABLE "django_migrations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, '
    '"app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL);'
)


def qi(name):
    return '"' + name.replace('"', '""') + '"'


def ql(value):
    return "'" + value.replace("'", "''") + "'"


def _columns_of(text):
    return [part.strip().split()[0].strip('"') for part in text.split(",") if part.strip()]


def _statement_columns(statement, table):
    """Column list of a constraint/index statement on `table`, else None."""
    if f'ALTER TABLE {qi(table)} ' in statement:
        match = re.search(r"(?:FOREIGN KEY|UNIQUE) \(([^)]*)\)", statement)
        if match:
            kind = "fk" if "FOREIGN KEY" in statement else "unique"
            return kind, _columns_of(match.group(1))
    match = re.match(r'CREATE (UNIQUE )?INDEX .* ON ' + re.escape(qi(table)) + r' \((.*)\)', statement)
    if match:
        return ("unique" if match.group(1) else "index"), _columns_of(match.group(2))
    return None


def _find_statements(model, kind, columns):
    out = []
    for statement in model.get("create_sql", []):
        found = _statement_columns(statement, model["db_table"])
        if found and found[0] == kind and found[1] == columns:
            out.append(statement)
    return out


def _constraint_name(table, columns, suffix):
    return f"{table}_{'_'.join(columns)}_{suffix}"[:63]


class _Script:
    def __init__(self):
        self.sections = []

    def section(self, title):
        lines = []
        self.sections.append((title, lines))
        return lines

    def has_statements(self):
        return any(
            line and not line.startswith("--") for _, lines in self.sections for line in lines
        )

    def render(self):
        out = []
        for title, lines in self.sections:
            if lines:
                out += ["", f"-- {title}", *lines]
        return out


def _schema_sections(script, models, schema_findings):
    by_table = {m["db_table"]: m for m in models}
    by_cat = {}
    for f in schema_findings:
        by_cat.setdefault(f["category"], []).append(f)

    # 1. Missing tables: every CREATE TABLE first, then constraints and indexes.
    lines = script.section("1. Missing tables")
    creates, deferred = [], []
    for f in by_cat.get("table_missing", []):
        model = by_table.get(f["table"])
        if f["severity"] != "error" or not model:
            continue
        for statement in model["create_sql"]:
            (creates if statement.startswith("CREATE TABLE") else deferred).append(statement)
    lines += creates + deferred

    # 2. Missing columns.
    lines = script.section("2. Missing columns")
    for f in by_cat.get("column_missing", []):
        model = by_table[f["table"]]
        column = next((c for c in model["columns"] if c["name"] == f["column"]), None)
        if column and not column["null"] and not column["has_default"] and not column["has_db_default"]:
            lines.append(f"-- WARNING: {f['table']}.{f['column']} is NOT NULL without a default; "
                         "this fails if the table has rows. Add a default or backfill first.")
        lines += model["add_column_sql"].get(f["column"], [f"-- could not generate SQL for {f['column']}"])

    # 3. Column changes.
    lines = script.section("3. Column changes")
    for f in by_cat.get("type_mismatch", []):
        model = by_table[f["table"]]
        raw = next((c["db_type"] for c in model["columns"] if c["name"] == f["column"]), f["data"]["expected"])
        lines.append(f"-- WARNING: {f['data']['actual']} -> {raw}; the cast may fail or lose data.")
        lines.append(f"ALTER TABLE {qi(f['table'])} ALTER COLUMN {qi(f['column'])} TYPE {raw} "
                     f"USING {qi(f['column'])}::{raw};")
    for f in by_cat.get("null_mismatch", []):
        if f["data"].get("expected_null"):
            lines.append(f"ALTER TABLE {qi(f['table'])} ALTER COLUMN {qi(f['column'])} DROP NOT NULL;")
        else:
            lines.append(f"-- WARNING: fails if {f['table']}.{f['column']} contains NULLs.")
            lines.append(f"ALTER TABLE {qi(f['table'])} ALTER COLUMN {qi(f['column'])} SET NOT NULL;")
    for f in by_cat.get("pk_mismatch", []) + by_cat.get("fk_wrong", []):
        lines.append(f"-- MANUAL: {f['table']}: {f['message']}")

    # 4. Missing constraints and indexes.
    lines = script.section("4. Missing foreign keys, unique constraints and indexes")
    for f in by_cat.get("fk_missing", []):
        model = by_table[f["table"]]
        found = _find_statements(model, "fk", [f["column"]])
        lines += found or [
            f"ALTER TABLE {qi(f['table'])} ADD CONSTRAINT "
            f"{qi(_constraint_name(f['table'], [f['column']], 'fk'))} FOREIGN KEY ({qi(f['column'])}) "
            f"REFERENCES {qi(f['data']['ref_table'])} ({qi(f['data']['ref_column'])}) DEFERRABLE INITIALLY DEFERRED;"
        ]
    for f in by_cat.get("unique_missing", []):
        model, columns = by_table[f["table"]], f["data"]["columns"]
        found = _find_statements(model, "unique", columns)
        lines += found or [
            f"ALTER TABLE {qi(f['table'])} ADD CONSTRAINT {qi(_constraint_name(f['table'], columns, 'uniq'))} "
            f"UNIQUE ({', '.join(qi(c) for c in columns)});"
        ]
    for f in by_cat.get("index_missing", []):
        model, columns = by_table[f["table"]], f["data"]["columns"]
        found = _find_statements(model, "index", columns)
        lines += found or [
            f"CREATE INDEX {qi(_constraint_name(f['table'], columns, 'idx'))} ON {qi(f['table'])} "
            f"({', '.join(qi(c) for c in columns)});"
        ]
    return by_cat


def _history_section(script, migration_findings, options):
    fake = options.get("history_strategy", "fake") == "fake"
    lines = script.section("5. Migration history (django_migrations)")
    by_cat = {}
    for f in migration_findings:
        by_cat.setdefault(f["category"], []).append(f)

    if by_cat.get("history_missing") and fake:
        lines.append(DJANGO_MIGRATIONS_DDL)
    ghosts = by_cat.get("ghost", [])
    if ghosts:
        lines.append("-- WARNING: deleting history rows for migrations that are not in this branch.")
    for f in ghosts:
        lines.append(f'DELETE FROM "django_migrations" WHERE app = {ql(f["app"])} AND name = {ql(f["data"]["name"])};')
    for f in by_cat.get("other_app_rows", []):
        if options.get("include_other_apps"):
            for name in f["data"]["names"]:
                lines.append(f'DELETE FROM "django_migrations" WHERE app = {ql(f["app"])} AND name = {ql(name)};')
        else:
            lines.append(f"-- kept: {len(f['data']['names'])} row(s) for app '{f['app']}' (not in this branch)")
    for f in sorted(by_cat.get("unapplied", []), key=lambda f: (f["app"], f["data"]["name"])):
        insert = (f'INSERT INTO "django_migrations" (app, name, applied) '
                  f'VALUES ({ql(f["app"])}, {ql(f["data"]["name"])}, now());')
        if fake:
            lines.append(insert)
        elif f["severity"] == "error":
            lines.append(f"-- WARNING: {f['message']}")
            lines.append(f"-- {insert}")
        else:
            lines.append(f"-- left for manage.py migrate: {f['app']}.{f['data']['name']}")
    for f in by_cat.get("inconsistent", []) + by_cat.get("multiple_leaves", []):
        lines.append(f"-- MANUAL: {f['message']}")


def _extras_section(script, schema_by_cat):
    lines = script.section("6. Extras in the database (commented out; never run automatically)")
    for f in schema_by_cat.get("table_extra", []):
        lines.append(f"-- DROP TABLE {qi(f['table'])};")
    for f in schema_by_cat.get("column_extra", []):
        if f["severity"] == "error":
            lines.append(f"-- {f['table']}.{f['column']} blocks inserts; alternatively:")
            lines.append(f"-- ALTER TABLE {qi(f['table'])} ALTER COLUMN {qi(f['column'])} DROP NOT NULL;")
        lines.append(f"-- ALTER TABLE {qi(f['table'])} DROP COLUMN {qi(f['column'])};")


def build_fix_sql(*, header, models, schema_findings, migration_findings, pending_changes, options):
    script = _Script()
    schema_by_cat = _schema_sections(script, models, schema_findings)
    _history_section(script, migration_findings, options)
    _extras_section(script, schema_by_cat)

    out = [
        f"-- Schema Sync fix: {header['project']} @ {header['branch']} ({header['commit']}) -> "
        f"{header['database']}",
        f"-- Generated {header['generated']}. REVIEW BEFORE RUNNING. Generated, not executed.",
        f"-- History strategy: {options.get('history_strategy', 'fake')}",
    ]
    pending = sum(len(ops) for ops in pending_changes.values())
    if pending:
        out.append(f"-- NOTE: {pending} model change(s) in this branch have no migration file; "
                   "the SQL below includes them, but the history rows will not.")
    if not script.has_statements():
        out += ["", "-- Nothing to do: the database matches the branch."]
        out += script.render()
        return "\n".join(out) + "\n"
    out += ["", "BEGIN;"]
    if header.get("schema", "public") != "public":
        out.append(f"SET LOCAL search_path TO {qi(header['schema'])};")
    out += script.render()
    out += ["", "COMMIT;"]
    return "\n".join(out) + "\n"


def build_commands(migration_findings, per_app, options):
    """manage.py equivalents of the history section."""
    commands = []
    for app in sorted({f["app"] for f in migration_findings if f["category"] == "ghost"}):
        commands.append(f"python manage.py migrate {app} --prune")
    if options.get("history_strategy", "fake") == "fake":
        for app in sorted({f["app"] for f in migration_findings if f["category"] == "unapplied"}):
            leaves = per_app.get(app, {}).get("disk_leaf", [])
            if len(leaves) == 1:
                commands.append(f"python manage.py migrate {app} {leaves[0]} --fake")
    return commands
