from django.urls import path

from . import views, views_data

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("batches/<uuid:batch_id>/", views.batch_detail, name="batch_detail"),
    path("runs/", views.run_list, name="run_list"),
    path("runs/<int:pk>/", views.run_detail, name="run_detail"),
    path("runs/<int:pk>/fix.sql", views.run_fix_sql, name="run_fix_sql"),
    path("runs/<int:pk>/report.json", views.run_report_json, name="run_report_json"),
    path("projects/", views.project_list, name="project_list"),
    path("projects/new/", views.project_form, name="project_create"),
    path("projects/<int:pk>/edit/", views.project_form, name="project_edit"),
    path("projects/<int:pk>/check/", views.project_check, name="project_check"),
    path("projects/<int:pk>/delete/", views.delete_object, {"kind": "project"}, name="project_delete"),
    path("databases/", views.database_list, name="database_list"),
    path("databases/new/", views.database_form, name="database_create"),
    path("databases/<int:pk>/edit/", views.database_form, name="database_edit"),
    path("databases/<int:pk>/test/", views.database_test, name="database_test"),
    path("databases/<int:pk>/delete/", views.delete_object, {"kind": "database"}, name="database_delete"),
    path("data/", views_data.data_home, name="data_home"),
    path("data/project/", views_data.data_project, name="data_project"),
    path("data/<int:db>/", views_data.data_tables, name="data_tables"),
    path("data/<int:db>/t/<str:table>/", views_data.data_table, name="data_table"),
    path("data/<int:db>/t/<str:table>/r/<str:pk>/", views_data.data_row, name="data_row"),
    path("ops/", views_data.op_list, name="op_list"),
    path("ops/new/", views_data.op_new, name="op_new"),
    path("ops/<int:pk>/", views_data.op_detail, name="op_detail"),
    path("ops/<int:pk>/preview/", views_data.op_repreview, name="op_repreview"),
    path("ops/<int:pk>/execute/", views_data.op_execute, name="op_execute"),
    path("ops/<int:pk>/restore.sql", views_data.op_restore, name="op_restore"),
    path("ops/<int:pk>/backup/<path:name>", views_data.op_backup_file, name="op_backup_file"),
    path("recipes/", views_data.recipe_list, name="recipe_list"),
    path("recipes/new/", views_data.recipe_form, name="recipe_create"),
    path("recipes/<int:pk>/edit/", views_data.recipe_form, name="recipe_edit"),
    path("recipes/<int:pk>/delete/", views_data.recipe_delete, name="recipe_delete"),
    path("recipes/<int:pk>/run/", views_data.recipe_run, name="recipe_run"),
    path("jobs/<int:pk>/", views_data.job_detail, name="job_detail"),
    path("jobs/<int:pk>.json", views_data.job_json, name="job_json"),
    path("jobs/<int:pk>/cancel/", views_data.job_cancel, name="job_cancel"),
]
