# Generated by Django 5.2.17 on 2026-10-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(default="", max_length=40),
        ),
    ]
